[workspace]
members = [
    "src-tauri",
    "dpi-core"
]
resolver = "2"

[profile.release]
lto = true          # Full Link-Time Optimization — maximální odstranění mrtvého kódu
opt-level = "z"     # Optimalizace na velikost
codegen-units = 1   # Lepší deduplikace kódu
panic = "abort"     # Odstraní unwinding tabulky
strip = true        # Strip debug symbolů
